version: "3.8"
services:
  backend:
    image: "codersergg/springboot-react-fullstack:19.9.2021.19.30.56"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev